# -*- coding: utf-8 -*-
"""clg project(translator) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NAzOjQBsIVNKNI8W-EXmw-Ia7gEb1tsi
"""

import torch
import numpy as np
!pip install evaluate sacrebleu transformers -U
import evaluate
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq,
)

# --- 1. Configuration & Device Setup ---
# Use the official English-Hindi checkpoint
MODEL_CHECKPOINT = "Helsinki-NLP/opus-mt-en-hi"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MAX_LENGTH = 128  # Defined MAX_LENGTH for the tokenizer

print(f"Running on device: {DEVICE}")

# --- 2. Load Model and Tokenizer (Fix for NameError) ---
# This ensures tokenizer and model are defined before the trainer setup
try:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT)
    if DEVICE == "cuda":
        model.to(DEVICE)
    print("Model and Tokenizer loaded successfully.")
except Exception as e:
    print(f"Error loading model/tokenizer: {e}")
    # Exit if we can't load the essentials
    exit()

# --- 3. Load Dataset (Fix for Performance/Dataset Error) ---
# Switched to a smaller subset of the cfilt/iitb-english-hindi dataset for speed.
# Change '[:50000]' to a larger number (e.g., '[:500000]') for better quality.
try:
    raw_datasets = load_dataset('cfilt/iitb-english-hindi', split='train[:50000]')
    # Split the loaded portion into train and test
    raw_datasets = raw_datasets.train_test_split(train_size=0.9, seed=42)
    print(f"Dataset loaded. Train size: {len(raw_datasets['train'])}, Test size: {len(raw_datasets['test'])}")
except Exception as e:
    print(f"Error loading dataset: {e}")
    exit()

def preprocess_function(examples):
    # The 'cfilt/iitb-english-hindi' dataset has keys 'translation' -> 'en' and 'hi'
    # When batched=True, examples['translation'] is a list of dictionaries.
    english_sentences = [item["en"] for item in examples["translation"]]
    hindi_sentences = [item["hi"] for item in examples["translation"]]

    # Tokenize English (Source)
    model_inputs = tokenizer(english_sentences, max_length=MAX_LENGTH, truncation=True)

    # Tokenize Hindi (Target) and set as labels for Seq2Seq
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(hindi_sentences, max_length=MAX_LENGTH, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# Apply the preprocessing to the entire dataset
tokenized_datasets = raw_datasets.map(
    preprocess_function,
    batched=True,
    remove_columns=raw_datasets["train"].column_names,
    num_proc=4,
)

# Correctly rename the 'test' split to 'validation'
tokenized_datasets["validation"] = tokenized_datasets.pop("test")

print("\nSample tokenized input_ids and labels (target):")
print(f"Input IDs: {tokenized_datasets['train'][0]['input_ids'][:10]}")
print(f"Labels: {tokenized_datasets['train'][0]['labels'][:10]}")

# Fix: Ensure evaluate and sacrebleu are installed before import
!pip install evaluate sacrebleu -q # -q for quiet output

import evaluate

metric = evaluate.load("sacrebleu")

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels] # SacreBLEU expects references as a list of lists
    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    # Decode predictions back to text
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    # Replace -100 in labels as we can't decode them.
    # Trainer puts -100 in padding tokens and special tokens.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Post-process for SacreBLEU (stripping whitespace and formatting references)
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    # Compute the BLEU score
    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"bleu": result["score"]} # Extract the 'score' key for BLEU

    # You can also compute average generation length if needed
    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)

    return result

# --- 5. Metrics Definition ---
metric = evaluate.load("sacrebleu")

def postprocess_text(preds, labels):
    preds = [pred.strip() for pred in preds]
    labels = [[label.strip()] for label in labels]
    return preds, labels

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]

    # Decode predictions
    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)
    # Replace -100 in the labels as we can't decode them.
    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    # Decode labels
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    # Post-process for SacreBLEU
    decoded_preds, decoded_labels = postprocess_text(decoded_preds, decoded_labels)

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    result = {"bleu": result["score"]}

    prediction_lens = [np.count_nonzero(pred != tokenizer.pad_token_id) for pred in preds]
    result["gen_len"] = np.mean(prediction_lens)
    result = {k: round(v, 4) for k, v in result.items()}
    return result

from transformers import Seq2SeqTrainingArguments, Seq2SeqTrainer, DataCollatorForSeq2Seq
import torch # Ensure torch is imported for torch.cuda.is_available()
from datasets import load_dataset # Import for dataset loading

# --- Re-load Model and Tokenizer if not defined for robustness ---
# This section ensures 'tokenizer' and 'model' are available,
# in case the cell defining them (e.g., cell 6QVgpPuI1Pwn) was not run
# or its state was lost.
if 'tokenizer' not in globals() or 'model' not in globals():
    print("Tokenizer or model not found in global scope. Re-loading them...")
    # MODEL_CHECKPOINT and DEVICE are assumed to be defined by previous cells and are in kernel state
    try:
        tokenizer = AutoTokenizer.from_pretrained(MODEL_CHECKPOINT)
        model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_CHECKPOINT)
        if DEVICE == "cuda":
            model.to(DEVICE)
        print("Model and Tokenizer re-loaded successfully within this cell's scope.")
    except Exception as e:
        print(f"Error re-loading model/tokenizer: {e}")
        raise # Critical error, stop execution

# --- Ensure tokenized_datasets is available ---
if 'tokenized_datasets' not in globals():
    print("tokenized_datasets not found in global scope. Re-loading and tokenizing dataset...")
    try:
        # Load raw dataset (from WI_kjOJ01Uqp)
        raw_datasets = load_dataset('cfilt/iitb-english-hindi', split='train[:50000]')
        raw_datasets = raw_datasets.train_test_split(train_size=0.9, seed=42)
        print(f"Dataset loaded. Train size: {len(raw_datasets['train'])}, Test size: {len(raw_datasets['test'])}")

        # Define preprocess_function (from Ja1rkXRmd1pL)
        def preprocess_function(examples):
            english_sentences = [item["en"] for item in examples["translation"]]
            hindi_sentences = [item["hi"] for item in examples["translation"]]
            model_inputs = tokenizer(english_sentences, max_length=MAX_LENGTH, truncation=True)
            with tokenizer.as_target_tokenizer():
                labels = tokenizer(hindi_sentences, max_length=MAX_LENGTH, truncation=True)
            model_inputs["labels"] = labels["input_ids"]
            return model_inputs

        # Apply the preprocessing (from Ja1rkXRmd1pL)
        tokenized_datasets = raw_datasets.map(
            preprocess_function,
            batched=True,
            remove_columns=raw_datasets["train"].column_names,
            num_proc=4, # Use num_proc=1 if you encounter multiprocessing issues in some environments
        )
        tokenized_datasets["validation"] = tokenized_datasets.pop("test")
        print("Dataset re-tokenized successfully within this cell's scope.")

    except Exception as e:
        print(f"Error re-loading/tokenizing dataset: {e}")
        raise # Critical error, stop execution

# --- 6. Training Arguments and Trainer Setup (Fix Applied) ---
training_args = Seq2SeqTrainingArguments(
    output_dir="./final_en_hi_translator",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    num_train_epochs=3,
    save_total_limit=3,
    fp16=torch.cuda.is_available(),
    predict_with_generate=True,
    logging_dir='./logs',
)

data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# --- 7. Start Fine-Tuning (Now it should run without NameError) ---
print("\n--- Starting Fine-Tuning ---")
print("NOTE: Training time is now significantly reduced due to the smaller dataset slice (50k).")
# trainer.train()

# 8. Save the final fine-tuned model (Uncomment after successful training)
# trainer.save_model("./final_en_hi_translator")

# --- 9. Inference Function (To be used in the Gradio App) ---
# Ensure MODEL_CHECKPOINT is defined for this cell's execution context
MODEL_CHECKPOINT = "Helsinki-NLP/opus-mt-en-hi" # Re-defining it here for robustness

def translate_text(english_text, model_path=MODEL_CHECKPOINT):
    # Load the model/tokenizer (or from the fine-tuned path)
    inference_tokenizer = AutoTokenizer.from_pretrained(model_path)
    inference_model = AutoModelForSeq2SeqLM.from_pretrained(model_path).to(DEVICE)

    # Tokenize the input text
    input_tokens = inference_tokenizer(
        english_text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH
    ).to(DEVICE)

    # Generate the translation using beam search for quality
    translated_tokens = inference_model.generate(
        **input_tokens,
        max_length=MAX_LENGTH,
        num_beams=6, # Higher beams for better quality translation
        early_stopping=True,
    )

    # Decode the generated tokens back to Hindi text
    hindi_text = inference_tokenizer.decode(
        translated_tokens[0],
        skip_special_tokens=True
    )
    return hindi_text

# Example Inference Usage (This will use the base model until you train and save the model)
print("\n--- Example Translation Test ---")
test_sentences = [
    "How are you today?",
    "My name is Shivam",
    "Machine translation models are very helpful.",
]
for sentence in test_sentences:
    translation = translate_text(sentence, model_path=MODEL_CHECKPOINT)
    print(f"English: {sentence} -> Hindi: {translation}")

import gradio as gr
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# --- 1. Configuration & Global Model Loading (CRITICAL FIX) ---
# Load model globally to prevent repeated loading and NameErrors,
# and to ensure the app doesn't crash if loading fails.
MODEL_PATH = "Helsinki-NLP/opus-mt-en-hi"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
MAX_LENGTH = 128

# Global Model and Tokenizer Initialization
try:
    GLOBAL_TOKENIZER = AutoTokenizer.from_pretrained(MODEL_PATH)
    # Move the model to the appropriate device (CPU or GPU)
    GLOBAL_MODEL = AutoModelForSeq2SeqLM.from_pretrained(MODEL_PATH).to(DEVICE)
    print(f"Model loaded successfully on {DEVICE}.")
except Exception as e:
    # If loading fails (e.g., due to network or environment issues), set placeholders
    print(f"CRITICAL: Failed to load global model/tokenizer from {MODEL_PATH}. Error: {e}")
    GLOBAL_TOKENIZER = None
    GLOBAL_MODEL = None


# --- 2. Translation Function (Uses Global Model) ---
def translate_text(english_text):
    if not english_text:
        return "Input text cannot be empty."

    # Check if the model loaded globally before proceeding
    if GLOBAL_MODEL is None or GLOBAL_TOKENIZER is None:
        return "Error: Translation model not loaded. Check startup console for details."

    # Use the globally loaded model and tokenizer
    tokenizer = GLOBAL_TOKENIZER
    model = GLOBAL_MODEL

    # Tokenize the input text
    input_tokens = tokenizer(
        english_text,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=MAX_LENGTH
    ).to(DEVICE)

    # Generate the translation using beam search for quality
    translated_tokens = model.generate(
        **input_tokens,
        max_length=MAX_LENGTH,
        num_beams=6,
        early_stopping=True,
    )

    # Decode the generated tokens back to Hindi text
    hindi_text = tokenizer.decode(
        translated_tokens[0],
        skip_special_tokens=True
    )
    return hindi_text

# --- 3. Gradio Interface Setup ---
# Consolidated CSS from the various fragmented attempts in the original notebook state
css = """
body {
    background-color: #e5e5f7;
    background-image:
        repeating-radial-gradient(circle at 0 0, transparent 0, #e5e5f7 27px),
        repeating-linear-gradient(#daa52355, #daa523),
        linear-gradient(120deg, #fff3c4, #ffe9a7, #f8d77c, #fff3c4);
    background-size: auto, auto, 400% 400%;
    background-attachment: fixed;
    animation: shimmerMove 12s ease-in-out infinite;
    font-family: 'Inter', sans-serif;
    color: #1a1a1a;
}

/* ===== Title & Description ===== */
h1 {
    color: #ffeb3b; /* bright yellow, combined from the original Gradio.Interface call */
    text-align: center;
    font-weight: 2000;
    text-shadow: 0 0 2px #ffeb3b, 0 0 4px #ffd54f;
    margin-bottom: 20px;
}
.gradio-container p { /* Targeting all p in gradio-container, might be too broad */
    color: #333;
    text-align: center;
    font-size: 50px; /* This is very large, assuming it was intended for the description */
}

/* ===== Labels ===== */
.label {
    font-size: 18px !important; /* from first block */
    font-weight: 950; /* from second block (overwrites 600 from first) */
    color: #000 !important;
}

/* ===== Text Areas ===== */
textarea {
    min-height: 300px !important;
    min-width: 100% !important;
    resize: none !important;
    border-radius: 16px !important;
    font-size: 20px !important;
    font-weight: 500 !important;
    line-height: 1.6 !important;
    padding: 20px !important;
    color: #000 !important;
    background: rgba(255, 255, 255, 0.85) !important;
    border: 2px solid #daa523 !important;
    box-shadow: 0 4px 15px rgba(218, 165, 35, 0.3);
    transition: all 0.3s ease;
}

textarea:focus {
    outline: none !important;
    border: 2px solid #ffcc00 !important;
    box-shadow: 0 0 15px rgba(255, 221, 0, 0.6);
}

.gr-textarea { /* Specific Gradio textarea styling */
    border: 1px solid #ccc !important;
    background: rgba(255, 255, 255, 0.85) !important;
    color: #000 !important;
    border-radius: 10px !important;
}


/* ===== Buttons ===== */
.gr-button-primary {
    margin-top: 10px; /* from first block */
    font-size: 18px !important; /* from first block */
    padding: 10px 25px !important; /* from first block */
    background-color: #daa523;
    color: #fff;
    border: none;
    border-radius: 10px;
    transition: all 0.3s ease;
    font-weight: 900; /* from second block (overwrites 600 from first) */
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
}
.gr-button-primary:hover {
    background-color: #f1b733;
    transform: translateY(-2px);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.25);
}

/* ===== Secondary buttons (Clear, Flag) ===== */
button:not(.gr-button-primary) {
    background-color: rgba(0, 0, 0, 0.05);
    color: #000;
    border-radius: 10px;
}
button:not(.gr-button-primary):hover {
    background-color: rgba(0, 0, 0, 0.15);
}

/* ===== Footer ===== */
footer, .footer {
    color: #444 !important;
}
"""

iface = gr.Interface(
    fn=translate_text,
    inputs=gr.Textbox(
        lines=5,
        label="English Input",
        placeholder="Enter text here (e.g., I want a cup of tea)"
    ),
    outputs=gr.Textbox(
        lines=5,
        label="Hindi Translation (हिंदी अनुवाद)",
        placeholder="Translation will appear here"
    ),
    title="✨English to Hindi Machine Translaton Model (DL Project)✨",
    description="This application uses a Hugging Face Sequence-to-Sequence model (Helsinki-NLP/opus-mt-en-hi). The current deployment uses the base model for speed; better results require full fine-tuning. The model provides high-quality, contextually meaningful Hindi translations.",
    css= """
h1 {
    color: #ffeb3b; /* bright yellow */
    text-align: center;
    font-weight: 2000;
    text-shadow: 0 0 2px #ffeb3b, 0 0 1px #ffd54f;
}
""", # Pass the consolidated CSS string
    theme=gr.themes.Soft(primary_hue="yellow", secondary_hue="gray") # Correctly pass the theme object
)

if __name__ == "__main__":
    print(f"Gradio app initializing. Model path set to: {MODEL_PATH}")
    # Before launching, it's a good practice to ensure a clean state if `transformers` was just updated
    # This often involves restarting the runtime after a major library update that affects internal structure.
    # After restarting the runtime and re-running all cells, uncomment the line below to launch the app:
    # iface.launch(share=True)

iface.launch(share=True)

